### ISSUE TITLE
DF beta bug in Chris's fork

### ISSUE THREAD

**Issue by ZINK-ZINK** [silverwind/idTip#82]
This is while using the beta fork build from about October 4th. https://github.com/ItsJustMeChris/idTip/tree/beta

1x Interface/AddOns/idTip/idTip.lua:220: hooksecurefunc(): SetTooltipRecipeResultItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/idTip/idTip.lua"]:220: in main chunk

Locals:

**Comment by ItsJustMeChris** [comment]
I'll fix it as soon as I have time. Been busy for the last week. Looks like blizzard just changed some more stuff 😒

**Comment by yoshimo** [comment]
The PTR and the beta realms differ, so keep that in mind as well.
Talents on PTR have no working tooltip for me

**Comment by ItsJustMeChris** [comment]
Ya I dump the interface files for beta not ptr but I can maybe look there too 🤷‍♂️ maybe it's better since they're calling it a release candidate.

**Comment by ZINK-ZINK** [comment]
The error started at the same time the Tooltip anchor became movable in Edit Mode. idTip still works mostly. So my guess is it's just trying to use frame hooks that have changed filenames.

**Comment by ItsJustMeChris** [comment]
fixed here https://github.com/ItsJustMeChris/idTip/commit/f69389e0bfc30ee8b06a5d2f7e76efb29fc0a060

**Comment by Asaelle** [comment]
Thanks for update, but CreatureId are still not displayed on tooltip

**Comment by ZINK-ZINK** [comment]
Thanks, appreciate ya dude. :D It's amazing how much QoL such a small addon provides. Trying to make weakauras without it was torture

**Comment by ItsJustMeChris** [comment]
@Asaelle I'll have to take a look a bit later. I'm not home until tomorrow so difficult to find the time..

@ZINK-ZINK it sure is, glad to help maintain it as best I can, if you ever think of anything more to add feel free to leave a suggestion..

**Comment by ItsJustMeChris** [comment]
I've enabled issues on my fork. 

I'm going to start assuming that silverwind no longer wants to maintain the project as there's been no communication for months, and I'll consider my fork as a community fork for all future changes and additions. 

https://github.com/ItsJustMeChris/idTip-Community-Fork-/issues

**Comment by ItsJustMeChris** [comment]
@Asaelle NPC and item is fixed in my last commit, gotta head to the airport soon.. possibly currencies are also not working and some other stuff related to items, but ill need test a lot more extensively I think to know for sure.

**Comment by silverwind** [comment]
Should all be fixed now.
